### ISSUE TITLE
Running via a Python 2 interpreter fails in a non-obvious way

### ISSUE THREAD

**Issue by follower** [dgonner/gerber2png.py#1]
While I recognize that `gerber2png.py` is probably intentionally written to only support Python 3 I tried running it with a Python 2 interpreter because that's what I had on the machine at hand.

It failed--but in a non-obvious way--and it turns out that the "fix" is pretty simple to make when one works out what needs to change.

### Underlying cause

The underlying issue occurs with lines like:

```python
if type(p) == Circle:
```

Because `Circle` is an "old-style" class under Python 2 the output of `type()` has different results:

```python
class Foo:
   pass

f = Foo()

print(type(f))
# Result under Python 2: <type 'instance'>
# Result under Python 3: <class '__main__.Foo'>
```

### Potential solutions

There's a couple of options for enabling this code to run under both Python 2 & Python 3:

 * "Duck typing" -- checks such as `hasattr(p, "diameter")` & `hasattr(p, "width")`
 * Use of `isinstance()` -- e.g. `isinstance(p, Circle)`& `isinstance(p, Rect)`

I figure the latter option more closely matches the intention of the original code so plan to submit a patch of that form. I understand if Python 2 support is explicitly not wanted but at least then a patch is available for those who might want it for themselves.

### Comparison of output result

AFAICT the resulting images are almost exactly the same with Python 2 & 3--the only exception is that there are 1 pixel differences in some places on some tracks. I'm guessing this could be a difference in rounding in the underlying pillow library or something? Whatever the cause, at the output sizes we're dealing with I don't think a 1-pixel difference will have an impact.

### A note about `round()`-ing

A side note about rounding: I had originally thought the issue might have been due to difference in `round()` operation between the two versions but AFAICT it wasn't a factor. But here's a re-implementation of `round()` ([via](https://stackoverflow.com/questions/21839140/python-3-rounding-behavior-in-python-2#21840060)) I used if it becomes an issue in future:

```python
if round(0.5) != 0:
      def round(value):
              if abs(__builtins__.round(value)-value) == 0.5:
                      return 2.0*__builtins__.round(value/2.0);
              return __builtins__.round(value)
```

**Comment by dgonner** [comment]
Hi, thank you for your contribution!
I just chose python 3 because I consider 2.7 deprecated and new projects should use python 3.
That being said, I do recognize that in some situations only 2.7 is available.
It's been quite a while since I last used this script so it is not under 'active development'. 
I am happy to accept your patch, but I don't have the time right now to test it thoroughly.
